# generated by run.sh: re-add cdk-erigon-sequencer-001 with image hermeznetwork/cdk-erigon:v2.61.24, config artifact cdk-erigon-sequencer-config-pp and its persistent datadir
def run(plan, args):
    plan.remove_service(name="cdk-erigon-sequencer-001")
    plan.add_service(
        name="cdk-erigon-sequencer-001",
        config=ServiceConfig(
            image="hermeznetwork/cdk-erigon:v2.61.24",
            ports={"data-streamer": PortSpec(number=6900, transport_protocol="TCP", application_protocol="datastream", wait="3m"), "pprof": PortSpec(number=6060, transport_protocol="TCP", wait="3m"), "prometheus": PortSpec(number=9091, transport_protocol="TCP", wait="3m"), "rpc": PortSpec(number=8545, transport_protocol="TCP", application_protocol="http", wait="3m"), "ws-rpc": PortSpec(number=8546, transport_protocol="TCP", application_protocol="ws", wait="3m")},
            files={"/etc/cdk-erigon": Directory(artifact_names=["cdk-erigon-sequencer-config-pp","cdk-erigon-sequencer-chain-spec-001","cdk-erigon-chain-config","cdk-erigon-chain-allocs","cdk-erigon-chain-first-batch"]), "/home/erigon/dynamic-configs/": Directory(artifact_names=["cdk-erigon-sequencer-chain-spec-001","cdk-erigon-chain-config","cdk-erigon-chain-allocs","cdk-erigon-chain-first-batch"]), "/usr/local/share/proc-runner": Directory(artifact_names=["cdk-erigon-sequencer-proc-runner-001"]), "/home/erigon/data/dynamic-kurtosis-sequencer": Directory(persistent_key="cdk-erigon-datadir-001")},
            entrypoint=["/usr/local/share/proc-runner/proc-runner.sh"],
            cmd=["cdk-erigon --config /etc/cdk-erigon/config.yaml"],
            env_vars={"CDK_ERIGON_SEQUENCER":"1","PATH":"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"},
            user=User(uid=0, gid=0),
        ),
    )

