services:
  agglayer-prover:
    image: ${AGGLAYER_IMAGE}
    container_name: agglayer-prover
    networks:
      - kt-network
    environment:
      - NETWORK_PRIVATE_KEY=${SP1_NETWORK_KEY}
      - SP1_PRIVATE_KEY=${SP1_NETWORK_KEY}
      - NETWORK_RPC_URL=${NETWORK_RPC_URL}
      # - RUST_LOG=info
      # - RUST_BACKTRACE=1
    volumes:
      - ./agglayer-prover-config.toml:/etc/zkevm/agglayer-prover-config.toml
    entrypoint: /usr/local/bin/agglayer
    command: prover --cfg /etc/zkevm/agglayer-prover-config.toml
    healthcheck:
      test: ["CMD-SHELL", "cat /proc/net/tcp | grep 115D"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

  agglayer:
    image: ${AGGLAYER_IMAGE}
    container_name: agglayer
    networks:
      - kt-network
    volumes:
      - ./zkevm:/etc/zkevm
      # - ./agglayer-config.toml:/etc/zkevm/agglayer-config.toml
      # - ./agglayer.keystore:/etc/zkevm/agglayer.keystore
    entrypoint: /usr/local/bin/agglayer
    command: run --cfg /etc/zkevm/agglayer-config.toml
    depends_on:
      agglayer-prover:
        condition: service_healthy
    restart: on-failure:5 # Restart up to 5 times on failure
    healthcheck:
      test: ["CMD-SHELL", "curl -f 0.0.0.0:9092/metrics || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

networks:
  kt-network:
      name: kt-${ENCLAVE_NAME}
      external: true