#!/usr/bin/env python3
"""
Generate docs/POS_VERSION_MATRIX.md from extracted PoS version data.

Reads scripts/version-matrix/matrix.json and creates a human-readable
Markdown document with version tables, status indicators, and links.
"""

import json
from pathlib import Path
from typing import Dict


STATUS_EMOJI = {
    "newer than stable": "\u26a1\ufe0f",   # ⚡️
    "matches stable": "\u2705",             # ✅
    "behind stable": "\U0001f6a8",          # 🚨
}


class MarkdownMatrixGenerator:
    """Generates Markdown version matrix from extracted data."""

    def __init__(self, repo_root: Path):
        self.repo_root = repo_root
        self.matrix_json_path = repo_root / "scripts" / "version-matrix" / "matrix.json"
        self.output_path = repo_root / "docs" / "POS_VERSION_MATRIX.md"

    def load_matrix_data(self) -> Dict:
        if not self.matrix_json_path.exists():
            raise FileNotFoundError(f"Matrix data not found at {self.matrix_json_path}")
        with open(self.matrix_json_path) as f:
            return json.load(f)

    def generate(self, data: Dict) -> str:
        md = "# PoS Version Compatibility Matrix\n\n"
        md += "> This document is automatically generated by "
        md += "`scripts/version-matrix/generate-markdown.py`.\n"
        md += f"> Last updated: {data.get('generated_at', 'unknown')}\n\n"

        # ----- Default images (from kurtosis-pos constants.star) -----
        md += "## Default Images (kurtosis-pos)\n\n"
        md += "These are the default component images defined in "
        md += "[kurtosis-pos constants.star]"
        md += "(https://github.com/0xPolygon/kurtosis-pos/blob/main/src/config/constants.star).\n\n"
        md += self._component_table(data.get("default_images", {}))

        # ----- Test environments -----
        test_envs = data.get("test_environments", {})
        if test_envs:
            md += "\n## Test Environments\n\n"
            md += "Component versions used in each E2E test scenario.\n\n"

            for env_key in sorted(test_envs):
                env = test_envs[env_key]
                env_type = env.get("type", env_key)
                config = env.get("config_file_path", "")
                components = env.get("components", {})

                md += f"### {env_type}\n\n"
                if config:
                    md += f"- Config: `{config}`\n\n"
                md += self._component_table(components)
                md += "\n"

        # ----- Status legend -----
        md += "## Status Legend\n\n"
        md += "| Status | Icon | Description |\n"
        md += "|--------|------|-------------|\n"
        md += "| matches stable | \u2705 | Version matches the latest release (including pre-release) |\n"
        md += "| newer than stable | \u26a1\ufe0f | Ahead of the latest release |\n"
        md += "| behind stable | \U0001f6a8 | Older than the latest release |\n"

        return md

    @staticmethod
    def _component_table(components: Dict) -> str:
        """Render a component table with version, latest release, latest stable, and status."""
        table = "| Component | Version Deployed | Latest Release | Latest Stable | Status |\n"
        table += "|-----------|-----------------|----------------|---------------|--------|\n"

        for name in sorted(components):
            comp = components[name]
            version = comp.get("version", "N/A")
            v_url = comp.get("version_source_url")
            latest = comp.get("latest_version", "N/A")
            l_url = comp.get("latest_version_source_url")
            latest_stable = comp.get("latest_stable_version")
            ls_url = comp.get("latest_stable_version_source_url")
            status = comp.get("status")

            v_display = f"[{version}]({v_url})" if v_url else version
            l_display = f"[{latest}]({l_url})" if l_url else str(latest)
            ls_display = f"[{latest_stable}]({ls_url})" if ls_url and latest_stable else (str(latest_stable) if latest_stable else "-")

            emoji = STATUS_EMOJI.get(status, "\u2753")  # ❓
            s_display = f"{emoji} {status}" if status else "N/A"

            table += f"| {name} | {v_display} | {l_display} | {ls_display} | {s_display} |\n"

        return table

    def save(self, content: str):
        self.output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(self.output_path, "w") as f:
            f.write(content)
        print(f"Version matrix saved to {self.output_path}")


def main():
    repo_root = Path(__file__).resolve().parent.parent.parent
    gen = MarkdownMatrixGenerator(repo_root)

    print("Loading matrix data...")
    data = gen.load_matrix_data()

    print("Generating Markdown...")
    content = gen.generate(data)

    print("Saving...")
    gen.save(content)
    print("Done.")


if __name__ == "__main__":
    main()
