#!/usr/bin/env bats
# bats file_tags=pos,fork-activation,golden-state,regression

# Golden State Regression Tests
# ================================
# Verifies that block hashes at fork boundaries match a committed reference file.
#
# Motivation: A new Bor release that unintentionally changes state at a fork
# boundary (e.g., wrong precompile encoding, gas parameter mis-encoding) will
# produce a different blockHash at the activation block. This test catches that
# class of regression without requiring a cross-client oracle.
#
# How it works:
#   1. The golden file (tests/pos/golden/state-roots-<version>.json) is committed
#      to the repo and generated by scripts/compute-golden-state.sh against a
#      known-good release image.
#   2. This test queries the running devnet at the same block numbers recorded
#      in the golden file and asserts the hashes match.
#   3. If no golden file exists for the current version, the test skips (first-run
#      mode — run compute-golden-state.sh to generate one).
#
# When to update the golden file:
#   A legitimate state change (new fork, new precompile, gas schedule change) will
#   cause this test to fail intentionally. To update:
#     1. Run: ./scripts/compute-golden-state.sh --bor-version <new-version>
#     2. Review the diff carefully in the PR — every field change is a deliberate
#        on-chain state change that must be explained.
#     3. git add tests/pos/golden/state-roots-<version>.json
#     4. Commit: "pos: update golden state for Bor v<version> (reason: <fork name>)"
#
# REQUIREMENTS:
#   - Kurtosis enclave deployed with the fork-transition devnet
#   - BOR_MIN_VERSION (or BOR_VERSION) env var set to the release version
#   - Golden file at tests/pos/golden/state-roots-<version>.json
#
# RUN: bats tests/pos/execution-specs/fork-transitions/golden-state-regression.bats

# ────────────────────────────────────────────────────────────────────────────
# File-level setup
# ────────────────────────────────────────────────────────────────────────────

setup_file() {
    load "../../../../core/helpers/pos-setup.bash"
    pos_setup

    # Resolve golden file path
    # 2 levels up from fork-transitions/ → pos/ → golden/
    GOLDEN_DIR="$(cd "$(dirname "$BATS_TEST_FILENAME")/../../golden" && pwd)"
    export GOLDEN_DIR

    # Resolve Bor version: prefer BOR_VERSION, fall back to BOR_MIN_VERSION, then RPC query
    export GOLDEN_BOR_VERSION="${BOR_VERSION:-${BOR_MIN_VERSION:-}}"
    if [[ -z "$GOLDEN_BOR_VERSION" ]]; then
        local raw_version
        raw_version=$(curl -s -m 30 --connect-timeout 5 -X POST "${L2_RPC_URL}" \
            -H "Content-Type: application/json" \
            -d '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":1}' \
            | jq -r '.result // empty' 2>/dev/null || true)
        GOLDEN_BOR_VERSION=$(echo "$raw_version" \
            | grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+(-beta[0-9]*|-rc[0-9]*)?' | head -1 | sed 's/^v//')
    fi

    if [[ -n "$GOLDEN_BOR_VERSION" ]]; then
        export GOLDEN_FILE="${GOLDEN_DIR}/state-roots-${GOLDEN_BOR_VERSION}.json"
        echo "Golden file: ${GOLDEN_FILE}" >&3
        if [[ -f "$GOLDEN_FILE" ]]; then
            echo "Golden file found for Bor v${GOLDEN_BOR_VERSION}" >&3
        else
            echo "No golden file for Bor v${GOLDEN_BOR_VERSION} — tests will skip (first-run mode)" >&3
        fi
    else
        echo "WARNING: Could not determine Bor version — all tests will skip" >&3
        export GOLDEN_FILE=""
    fi
}

# ────────────────────────────────────────────────────────────────────────────
# Per-test setup
# ────────────────────────────────────────────────────────────────────────────

setup() {
    load "../../../../core/helpers/pos-setup.bash"
    load "../../../../core/helpers/scripts/eventually.bash"
    pos_setup

    # Skip if no golden file is available (first-run mode or version unknown)
    if [[ -z "${GOLDEN_FILE:-}" || ! -f "${GOLDEN_FILE:-}" ]]; then
        skip "No golden state file for Bor v${GOLDEN_BOR_VERSION:-unknown} — run scripts/compute-golden-state.sh to generate one"
    fi
}

# ────────────────────────────────────────────────────────────────────────────
# Helpers
# ────────────────────────────────────────────────────────────────────────────

# Query a block field from the Bor RPC.
_block_field() {
    local block="$1" field="$2"
    local block_hex
    block_hex=$(printf '0x%x' "$block")
    curl -s -m 30 --connect-timeout 5 -X POST "${L2_RPC_URL}" \
        -H "Content-Type: application/json" \
        -d "{\"jsonrpc\":\"2.0\",\"method\":\"eth_getBlockByNumber\",\"params\":[\"${block_hex}\",false],\"id\":1}" \
        | jq -r --arg f "${field}" '.result[$f] // empty'
}

# Wait for the devnet to reach a minimum block height.
_wait_for_block() {
    local target="$1"
    local current
    current=$(cast block-number --rpc-url "${L2_RPC_URL}" 2>/dev/null || echo 0)
    [[ "$current" -ge "$target" ]] && return 0
    local remaining=$(( target - current ))
    local timeout=$(( remaining * 3 + 120 ))
    [[ "$timeout" -gt 1800 ]] && timeout=1800
    assert_command_eventually_greater_or_equal \
        "cast block-number --rpc-url ${L2_RPC_URL}" \
        "${target}" "${timeout}" 5
}

# Assert that a single fork entry from the golden file matches the live chain.
# $1: fork entry JSON (from .blocks[] in the golden file)
_assert_fork_entry_matches() {
    local entry="$1"
    local fork_name fork_block
    fork_name=$(echo "$entry" | jq -r '.fork_name')
    fork_block=$(echo "$entry" | jq -r '.fork_block')

    if [[ -z "$fork_name" || "$fork_name" == "null" ]]; then
        echo "  FAIL: entry has no fork_name — golden file may be malformed (fork_block=${fork_block:-unknown})" >&2
        return 1
    fi
    [[ -z "$fork_block" || "$fork_block" == "null" || "$fork_block" -le 0 ]] && return 0

    local failed=0

    # Check fork-1, fork, and fork+1
    for label in "fork-1" "fork" "fork+1"; do
        local golden_block golden_hash live_hash

        golden_hash=$(echo "$entry" | jq -r ".\"${label}\".hash // empty")
        golden_block=$(echo "$entry" | jq -r ".\"${label}\".number // empty")

        [[ -z "$golden_hash" || "$golden_hash" == "null" ]] && continue
        [[ -z "$golden_block" || "$golden_block" == "null" ]] && continue

        live_hash=$(_block_field "${golden_block}" "hash")

        if [[ -z "$live_hash" || "$live_hash" == "null" ]]; then
            echo "  WARN: Could not fetch block ${golden_block} (${fork_name} ${label}) from devnet" >&3
            continue
        fi

        if [[ "$live_hash" != "$golden_hash" ]]; then
            echo "REGRESSION at fork '${fork_name}' block ${golden_block} (${label}):" >&2
            echo "  expected (golden): ${golden_hash}" >&2
            echo "  actual (devnet):   ${live_hash}" >&2
            echo "" >&2
            echo "  This means state at or before this fork boundary has changed." >&2
            echo "  If this is intentional (new fork, gas schedule change, etc.):" >&2
            echo "    1. Review the change carefully" >&2
            echo "    2. Run: ./scripts/compute-golden-state.sh --bor-version ${GOLDEN_BOR_VERSION}" >&2
            echo "    3. Commit the updated golden file with justification in the commit message" >&2
            failed=1
        else
            echo "  OK ${fork_name} ${label} (block ${golden_block}): ${live_hash}" >&3
        fi
    done

    return "$failed"
}

# ────────────────────────────────────────────────────────────────────────────
# Tests
# ────────────────────────────────────────────────────────────────────────────

# bats test_tags=golden-state,regression,fork-transition
@test "golden-state: golden file is valid JSON and has expected structure" {
    run jq -e '.bor_version and .fork_schedule and (.blocks | length > 0)' "${GOLDEN_FILE}"
    [[ "$status" -eq 0 ]] || {
        echo "FAIL: Golden file ${GOLDEN_FILE} is missing required fields (bor_version, fork_schedule, blocks)" >&2
        echo "Output: $output" >&2
        return 1
    }

    local file_version
    file_version=$(jq -r '.bor_version' "${GOLDEN_FILE}")
    [[ "$file_version" == "$GOLDEN_BOR_VERSION" ]] || {
        echo "FAIL: Golden file bor_version '${file_version}' does not match expected '${GOLDEN_BOR_VERSION}'" >&2
        return 1
    }

    local block_count
    block_count=$(jq '.blocks | length' "${GOLDEN_FILE}")
    echo "  Golden file: Bor v${file_version}, ${block_count} fork entries" >&3
}

# bats test_tags=golden-state,regression,fork-transition
@test "golden-state: devnet is past the last fork in the golden file" {
    # Find the highest block number recorded in the golden file
    local last_block
    last_block=$(jq '[.blocks[].fork_block] | max' "${GOLDEN_FILE}")

    [[ -n "$last_block" && "$last_block" != "null" && "$last_block" -gt 0 ]] || {
        echo "FAIL: Could not determine last fork block from golden file" >&2
        return 1
    }

    echo "  Waiting for block $(( last_block + 5 )) (last golden fork: ${last_block})" >&3
    _wait_for_block $(( last_block + 5 ))
}

# bats test_tags=golden-state,regression,fork-transition
@test "golden-state: block hashes match at Rio fork boundary" {
    local entry
    entry=$(jq -c '.blocks[] | select(.fork_name == "rio")' "${GOLDEN_FILE}")
    [[ -z "$entry" ]] && skip "rio fork not in golden file"
    _assert_fork_entry_matches "$entry"
}

# bats test_tags=golden-state,regression,fork-transition
@test "golden-state: block hashes match at Madhugiri fork boundary" {
    local entry
    entry=$(jq -c '.blocks[] | select(.fork_name == "madhugiri")' "${GOLDEN_FILE}")
    [[ -z "$entry" ]] && skip "madhugiri fork not in golden file"
    _assert_fork_entry_matches "$entry"
}

# bats test_tags=golden-state,regression,fork-transition
@test "golden-state: block hashes match at MadhugiriPro fork boundary" {
    local entry
    entry=$(jq -c '.blocks[] | select(.fork_name == "madhugiriPro")' "${GOLDEN_FILE}")
    [[ -z "$entry" ]] && skip "madhugiriPro fork not in golden file"
    _assert_fork_entry_matches "$entry"
}

# bats test_tags=golden-state,regression,fork-transition
@test "golden-state: block hashes match at Dandeli fork boundary" {
    local entry
    entry=$(jq -c '.blocks[] | select(.fork_name == "dandeli")' "${GOLDEN_FILE}")
    [[ -z "$entry" ]] && skip "dandeli fork not in golden file"
    _assert_fork_entry_matches "$entry"
}

# bats test_tags=golden-state,regression,fork-transition
@test "golden-state: block hashes match at Lisovo fork boundary" {
    local entry
    entry=$(jq -c '.blocks[] | select(.fork_name == "lisovo")' "${GOLDEN_FILE}")
    [[ -z "$entry" ]] && skip "lisovo fork not in golden file"
    _assert_fork_entry_matches "$entry"
}

# bats test_tags=golden-state,regression,fork-transition
@test "golden-state: block hashes match at LisovoPro fork boundary" {
    local entry
    entry=$(jq -c '.blocks[] | select(.fork_name == "lisovoPro")' "${GOLDEN_FILE}")
    [[ -z "$entry" ]] && skip "lisovoPro fork not in golden file"
    _assert_fork_entry_matches "$entry"
}

# bats test_tags=golden-state,regression,fork-transition
@test "golden-state: block hashes match at Giugliano fork boundary" {
    local entry
    entry=$(jq -c '.blocks[] | select(.fork_name == "giugliano")' "${GOLDEN_FILE}")
    [[ -z "$entry" ]] && skip "giugliano fork not in golden file"
    _assert_fork_entry_matches "$entry"
}

# bats test_tags=golden-state,regression,fork-transition
@test "golden-state: all fork entries in the golden file pass hash comparison" {
    # Sweep test — catches any fork added to the golden file that doesn't have
    # its own per-fork test above. Also surfaces partial failures across all forks.
    local total_forks passed_forks failed_forks
    total_forks=$(jq '.blocks | length' "${GOLDEN_FILE}")
    passed_forks=0
    failed_forks=0

    while IFS= read -r entry; do
        local fork_name fork_block
        fork_name=$(echo "$entry" | jq -r '.fork')
        fork_block=$(echo "$entry" | jq -r '.fork_block')

        [[ "$fork_block" -le 0 ]] && continue

        if _assert_fork_entry_matches "$entry"; then
            (( passed_forks++ )) || true
        else
            (( failed_forks++ )) || true
        fi
    done < <(jq -c '.blocks[]' "${GOLDEN_FILE}")

    echo "  Golden state check: ${passed_forks}/${total_forks} fork entries matched, ${failed_forks} failed" >&3

    [[ "$failed_forks" -eq 0 ]] || {
        echo "" >&2
        echo "SUMMARY: ${failed_forks} fork(s) failed the golden state check." >&2
        echo "To regenerate the golden file for an intentional state change:" >&2
        echo "  ./scripts/compute-golden-state.sh --bor-version ${GOLDEN_BOR_VERSION}" >&2
        return 1
    }
}
