# Generate a Kurtosis Starlark script that removes a service and re-adds it with a new image, one
# files artifact swapped, and a persistent directory declared. Input: `kurtosis service inspect -o json`.
# Args: name image old new datadir pkey uid gid
#
# Why: `kurtosis service update` recreates the container without its persistent directories
# (observed: cdk-erigon reopened an empty datadir), while Directory(persistent_key=...) in Starlark
# reattaches the same data, the way kurtosis-cdk declares the sequencer datadir.
def port_spec:
  "PortSpec(number=\(.value.number), transport_protocol=\"TCP\""
  + (if .value.maybe_application_protocol then ", application_protocol=\(.value.maybe_application_protocol|tojson)" else "" end)
  + ", wait=\"3m\")";

"# generated by run.sh: re-add \($name) with image \($image), config artifact \($new) and its persistent datadir\n"
+ "def run(plan, args):\n"
+ "    plan.remove_service(name=\($name|tojson))\n"
+ "    plan.add_service(\n"
+ "        name=\($name|tojson),\n"
+ "        config=ServiceConfig(\n"
+ "            image=\($image|tojson),\n"
+ "            ports={" + ([.ports // {} | to_entries[] | "\(.key|tojson): " + port_spec] | join(", ")) + "},\n"
+ "            files={"
    + (([.files // {} | to_entries[] | "\(.key|tojson): Directory(artifact_names=\(.value | map(if . == $old then $new else . end) | tojson))"]
        + ["\($datadir|tojson): Directory(persistent_key=\($pkey|tojson))"]) | join(", ")) + "},\n"
+ "            entrypoint=\((.entrypoint // [])|tojson),\n"
+ "            cmd=\((.cmd // [])|tojson),\n"
+ "            env_vars=\((.env_vars // {})|tojson),\n"
+ "            user=User(uid=\($uid), gid=\($gid)),\n"
+ "        ),\n"
+ "    )\n"
