grpc-endpoint = "0.0.0.0:4445"
max-concurrency-limit = 100
max-request-duration = 300
max-buffered-queries = 100

[log]
environment = "production" # "production" or "development"
# level = "info"
level = "debug"
outputs = ["stderr"]
format = "json"

[telemetry]
prometheus-addr = "0.0.0.0:9093"

[primary-prover.network-prover]
proving-timeout = 900

[grpc]
# size is define in bytes e.g. 100 * 1024 * 1024
# same for `max-encoding-message-size`
# default value is equal to 4MB
max-decoding-message-size = 1073741824  # 1GB
