polygon_pos_package:
  participants:
    # validator nodes
    - kind: validator
      cl_type: heimdall-v2
      cl_image: local/heimdall-v2:0d27dfc
      el_type: bor
      el_image: local/bor:0fe4b0d
      count: 5
      el_bor_produce_witness: true

    # rpc nodes
    - kind: rpc
      cl_type: heimdall-v2
      cl_image: local/heimdall-v2:0d27dfc
      el_type: bor
      el_image: local/bor:0fe4b0d
      el_bor_produce_witness: true
      el_bor_sync_with_witness: false
    - kind: rpc
      cl_type: heimdall-v2
      cl_image: local/heimdall-v2:0d27dfc
      el_type: bor
      el_image: local/bor:0fe4b0d
      el_bor_produce_witness: false
      el_bor_sync_with_witness: true
    - kind: rpc
      cl_type: heimdall-v2
      cl_image: local/heimdall-v2:0d27dfc
      el_type: bor
      el_image: local/bor:0fe4b0d
      el_bor_produce_witness: true
      el_bor_sync_with_witness: true
    - kind: rpc
      cl_type: heimdall-v2
      cl_image: local/heimdall-v2:0d27dfc
      el_type: bor
      el_image: local/bor:0fe4b0d
      el_bor_produce_witness: false
      el_bor_sync_with_witness: false

  additional_services:
    - observability
    - test_runner
