polygon_pos_package:
  participants:
    # Bor validator nodes (4 validators, 3 active block producers)
    - kind: validator
      count: 4
      el_bor_produce_witness: true
      cl_type: heimdall-v2
      cl_image: 0xpolygon/heimdall-v2:0.6.0
      el_type: bor
      el_image: 0xpolygon/bor:2.5.8

    # Bor and erigon RPC nodes
    - kind: rpc
      count: 1
      cl_type: heimdall-v2
      cl_image: 0xpolygon/heimdall-v2:0.6.0
      el_type: bor
      el_image: 0xpolygon/bor:2.5.8
    
    - kind: rpc
      count: 1
      cl_type: heimdall-v2
      cl_image: 0xpolygon/heimdall-v2:0.6.0
      el_type: erigon
      el_image: 0xpolygon/erigon:v3.3.7
