prover-entrypoint = "http://agglayer-prover:4445"
debug-mode = true

# Only supported by fork 12+
# mock-verifier = true

[full-node-rpcs]

[proof-signers]

[rpc]
grpc-port = 4443
readrpc-port = 4444
admin-port = 4446
host = "0.0.0.0"
request-timeout = 180
# size is define in bytes e.g. 100 * 1024 * 1024
# same for `max_response_body_size`
# default value is equal to 10MB
max-request-body-size = 104857600

[prover.grpc]
# size is define in bytes e.g. 100 * 1024 * 1024
# same for `max-encoding-message-size`
# default value is equal to 4MB
max-decoding-message-size = 1073741824  # 1GB
max-encoding-message-size = 1073741824  # 1GB

[grpc]
max-decoding-message-size = 1073741824  # 1GB
max-encoding-message-size = 1073741824  # 1GB


[outbound.rpc.settle]
max-retries = 3
retry-interval = 7
confirmations = 1
settlement-timeout = 1200

[log]
# level = "info"
# we want debug visibility here for now
level = "debug"
outputs = ["stderr"]
format = "json"

[auth.local]
# Successfully created new keypair.
# Address:     0x7CE9e3112fa4c71c7A3307a0dDEDd86F456164D1
# Private key: 0xeaxxxxxxxxxxxxxxxxxxxxx
private-keys = [
    { path = "/etc/agglayer/agglayer.keystore", password = "" },
]

[l1]
chain-id = 1
node-url = "http://anvil:8545"
ws-node-url = "ws://anvil:8545"
rollup-manager-contract = "0x5132A183E9F3CB7C848b0AAC5Ae0c4f0491B7aB2"
polygon-zkevm-global-exit-root-v2-contract = ""
rpc-timeout = 45

[l2]
rpc-timeout = 45

[telemetry]
prometheus-addr = "0.0.0.0:9092"

# https://github.com/orgs/agglayer/discussions/213

[rate-limiting]
send-tx = "unlimited"
# [rate-limiting.send-tx]
# max-per-interval = 1
# time-interval = "15m"

[rate-limiting.network]

[epoch.block-clock]
epoch-duration = 300
genesis-block = 21766615

[shutdown]
runtime-timeout = 5

[certificate-orchestrator]
input-backpressure-buffer-size = 1000

[certificate-orchestrator.prover.sp1-local]

[storage]
db-path = "/var/agglayer/storage"

# [storage.backup]
# path = "/var/backups/agglayer"
# state-max-backup-count = 100
# pending-max-backup-count = 100
