name: docker-push

on:
  # Trigger the workflow on pull requests made to the main branch.
  push:
    branches: ["main"]

  # Allow manual triggering of the workflow.
  workflow_dispatch:
    inputs:
      checkout_ref:
        description: The branch, commit or tag to checkout
        type: string
        required: false

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: agglayer/e2e

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
      - uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0
      - uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get short commit id
        run: |
          short_commit_id=$(git rev-parse --short HEAD)
          echo "SHORT_COMMIT_ID=${short_commit_id}" >> "${GITHUB_ENV}"
          echo "SHORT_COMMIT_ID=${short_commit_id}"

      - name: Build and push image
        id: push
        uses: docker/build-push-action@14487ce63c7a62a4a324b0bfb37086795e31c6c1 # v6.16.0
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.SHORT_COMMIT_ID }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      # This step generates an artifact attestation for the image, which is an unforgeable statement about where and how
      # it was built. It increases supply chain security for people who consume the image.
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.SHORT_COMMIT_ID }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
