name: docker-build

on:
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Get short commit id
        run: |
          short_commit_id=$(git rev-parse --short HEAD)
          echo "SHORT_COMMIT_ID=${short_commit_id}" >> "${GITHUB_ENV}"
          echo "SHORT_COMMIT_ID=${short_commit_id}" # debug

      - name: Build image
        uses: docker/build-push-action@14487ce63c7a62a4a324b0bfb37086795e31c6c1 # v6.16.0
        with:
          push: false
