name: Standard Battery Tests

on:
  workflow_dispatch:
    inputs:
      agglayer-e2e-ref:
        description: "agglayer/e2e repo ref (branch, tag, or commit)"
        required: true
        type: string
      kurtosis-cdk-ref:
        description: "kurtosis-cdk repo ref (branch, tag, or commit)"
        required: true
        type: string
      kurtosis-enclave-name:
        description: "name of the kurtosis enclave to use"
        default: "cdk"
        required: false
        type: string

jobs:
  run-standard-battery-tests:
    runs-on: ubuntu-latest
    env:
      POLYCLI_VERSION: v0.1.83
    steps:
      - name: Checkout agglayer-e2e
        uses: actions/checkout@v4
        with:
            repository: agglayer/e2e
            ref: ${{ inputs.agglayer-e2e-ref }}
            path: agglayer-e2e

      - name: Checkout kurtosis-cdk
        uses: actions/checkout@v4
        with:
            repository: 0xPolygon/kurtosis-cdk
            ref: ${{ inputs.kurtosis-cdk-ref }}
            path: kurtosis-cdk

      - name: Install kurtosis
        shell: bash
        run: |
            echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
            sudo apt update
            sudo apt install -y kurtosis-cli=1.7.2
            kurtosis analytics disable
            kurtosis version

      - name: Install jq
        shell: bash
        run: |
            sudo apt update
            sudo apt install -y jq

      - name: Install yq
        shell: bash
        run: |
            pip3 install yq
            yq --version
    
      - name: Install foundry
        uses: foundry-rs/foundry-toolchain@de808b1eea699e761c404bda44ba8f21aba30b2c # v1.3.1
        with:
            version: v1.0.0

      - name: Install bats
        uses: bats-core/bats-action@3.0.0

      - name: Install polycli
        run: |
            polycli_version="${{ env.POLYCLI_VERSION }}"
            pushd $(mktemp -d) || exit 1
            curl -s -L "https://github.com/0xPolygon/polygon-cli/releases/download/${polycli_version}/polycli_${polycli_version}_linux_amd64.tar.gz" > polycli.tar.gz
            tar xf polycli.tar.gz
            mv polycli_* /usr/local/bin/polycli
            polycli version
            popd

      - name: Run Kurtosis CDK
        run: |
            pushd kurtosis-cdk || exit 1
            kurtosis run --enclave ${{ inputs.agglayer-e2e-ref }} .
            popd
            pushd agglayer-e2e || exit 1
            bats tests/cdk/e2e.bats
            popd

      - name: Inspect Kurtosis enclave
        run : |
            kurtosis enclave inspect ${{ inputs.agglayer-e2e-ref }}

      - name: Run e2e tests
        run: |
          set -eo pipefail
          pushd agglayer-e2e || exit 1
          set -a
          source ./tests/.env
          set +a
          bats --filter-tags standard $(find tests -name '*.bats')
          popd
