# Make sure to configure the agglayer/e2e Github Secrets before running this test
# The tests target cardona-24 and bali-35 networks.
name: Standard Battery Tests - RPC (Nightly)

on:
  schedule:
    # Run at 3:00 AM UTC every day
    - cron: '0 3 * * *'
  workflow_dispatch:
    inputs:
      agglayer-e2e-ref:
        description: "agglayer/e2e repo ref (branch, tag, or commit)"
        default: "main"
        required: true
        type: string
      max-parallel-runs:
        description: "strategy.max-parallel - how many matrix tests to run in parallel"
        default: 1
        required: true
        type: number

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  discover-standard-tests:
    runs-on: gke-shared-dev-runners
    env:
      AGGLAYER_E2E_REF: ${{ inputs.agglayer-e2e-ref || 'main' }}
    outputs:
      testfiles: ${{ steps.set-matrix.outputs.testfiles }}
    steps:
      - name: Checkout agglayer-e2e
        uses: actions/checkout@v4
        with:
          repository: agglayer/e2e
          ref: ${{ env.AGGLAYER_E2E_REF }}
          path: agglayer-e2e

      - name: Find standard-tagged bats files
        id: set-matrix
        run: |
            pushd agglayer-e2e || exit 1
            # strictly detect tags with file_tags=standard and test_tags=standard
            files=$(grep -rlP '#\s*bats\s+(?:file_tags|test_tags)=[^#]*\bstandard\b(?!-)' ./tests | grep '\.bats$' || true)
            echo "Found files:"
            echo "$files"
            # Remove empty lines and ensure valid JSON array without trailing empty string
            files_json=$(echo "$files" | awk NF | jq -R -s -c 'split("\n") | map(select(length > 0))')
            echo "Files array:"
            echo "$files_json"
            echo "testfiles=$files_json" >> $GITHUB_OUTPUT
            popd

  run-standard-battery-tests:
    runs-on: gke-shared-dev-runners
    needs: discover-standard-tests
    timeout-minutes: 180
    strategy:
      fail-fast: false
      max-parallel: ${{ fromJson(inputs.max-parallel-runs || '1') }}
      matrix:
        testfile: ${{ fromJson(needs.discover-standard-tests.outputs.testfiles) }}
        target-network: ["cardona", "bali"]
    env:
      POLYCLI_VERSION: v0.1.84
      AGGLAYER_E2E_REF: ${{ inputs.agglayer-e2e-ref || 'main' }}
      L1_RPC_ENDPOINT: ${{ secrets.L1_RPC_ENDPOINT }}
      L2_RPC_ENDPOINT: ${{ matrix.target-network == 'cardona' && secrets.L2_CARDONA_NIGHTLY_RPC_ENDPOINT || secrets.L2_BALI_NIGHTLY_RPC_ENDPOINT }}
      L1_FUNDED_PRIVATE_KEY: ${{ secrets.L1_FUNDED_PRIVATE_KEY }}
      L2_FUNDED_PRIVATE_KEY: ${{ secrets.L2_FUNDED_PRIVATE_KEY }}
      TARGET_NETWORK: ${{ matrix.target-network }}
    steps:
      - name: Debug environment variables
        run: |
          env | grep -E 'AGGLAYER_E2E_REF|TARGET_NETWORK'

      - name: Checkout agglayer-e2e
        uses: actions/checkout@v4
        with:
          repository: agglayer/e2e
          ref: ${{ env.AGGLAYER_E2E_REF }}
          path: agglayer-e2e

      - name: Install bats
        uses: bats-core/bats-action@3.0.0
        with:
          support-path: "${{ github.workspace }}/lib/bats-support"
          assert-path: "${{ github.workspace }}/lib/bats-assert"
          detik-path: "${{ github.workspace }}/lib/bats-detik"
          file-path: "${{ github.workspace }}/lib/bats-file"

      - name: Install polycli
        run: |
            polycli_version="${{ env.POLYCLI_VERSION }}"
            pushd $(mktemp -d) || exit 1
            curl -s -L "https://github.com/0xPolygon/polygon-cli/releases/download/${polycli_version}/polycli_${polycli_version}_linux_amd64.tar.gz" > polycli.tar.gz
            tar xf polycli.tar.gz
            sudo mv polycli_* /usr/local/bin/polycli
            polycli version
            popd

      - name: Install system utilities
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y jq xxd
      
      - name: Install yq
        shell: bash
        run: |
          sudo curl -L -o /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
          yq --version

      - name: Install foundry
        uses: foundry-rs/foundry-toolchain@de808b1eea699e761c404bda44ba8f21aba30b2c # v1.3.1
        with:
          version: v1.0.0 
          cache: false

      - name: Install pem certificate
        shell: bash
        env:
          POLYGON_CERT: ${{ secrets.POLYGON_CERT }}
        run: |
          sudo apt-get install -y ca-certificates
          echo "$POLYGON_CERT" | sudo tee /usr/local/share/ca-certificates/local-ca.crt > /dev/null
          sudo update-ca-certificates

      - name: Validate RPC Endpoint
        run: |
          cast chain-id --rpc-url ${{ secrets.L1_RPC_ENDPOINT }}
          if [[ "${{ matrix.target-network }}" == "cardona" ]]; then
            cast chain-id --rpc-url ${{ secrets.L2_CARDONA_NIGHTLY_RPC_ENDPOINT }}
          else
            cast chain-id --rpc-url ${{ secrets.L2_BALI_NIGHTLY_RPC_ENDPOINT }}
          fi

      - name: Validate test file existence
        run: |
          testfile="agglayer-e2e/${{ matrix.testfile }}"
          if [[ ! -f "$testfile" ]]; then
            echo "Test file $testfile does not exist"
            exit 1
          fi

      - name: Run e2e tests
        run: |
          pushd agglayer-e2e || exit 1

          # Load public environment variables based on target network
          if [[ "${{ matrix.target-network }}" == "cardona" ]]; then
            if [[ -f "tests/lxly/cardona.env" ]]; then
              set -a
              source tests/lxly/cardona.env
              set +a
            fi
          elif [[ "${{ matrix.target-network }}" == "bali" ]]; then
            if [[ -f "tests/lxly/bali.env" ]]; then
              set -a
              source tests/lxly/bali.env
              set +a
            fi
          else
            echo "Invalid target network detected: ${{ matrix.target-network }}. Expected 'cardona' or 'bali'."
            exit 1
          fi

          # Set extended timeout and confirmation settings for cast
          export ETH_RPC_TIMEOUT=2400

          # Set sensitive values from GitHub secrets
          export L1_RPC_URL="${{ env.L1_RPC_ENDPOINT }}"
          export L1_PRIVATE_KEY="${{ env.L1_FUNDED_PRIVATE_KEY }}"
          export L2_RPC_URL="${{ env.L2_RPC_ENDPOINT }}"
          export L2_PRIVATE_KEY="${{ env.L2_FUNDED_PRIVATE_KEY }}"

          bats --filter-tags standard ${{ matrix.testfile }}
          popd

      - name: Upload bridge tests suite artifacts
        if: always() && contains(matrix.testfile, 'bridge-tests-suite.bats')
        uses: actions/upload-artifact@v4
        with:
          name: bridge_tests_suite_output_artifacts_${{ matrix.target-network }}
          path: /tmp/bridge_test_results_*
          retention-days: 7