name: Test e2e
on: 
  push:
    branches:
      - '**'
  schedule:
    - cron: "0 2 * * *"  # Run nightly at 2 AM UTC
  workflow_dispatch: {}

jobs:
  test-e2e:
    strategy:
      fail-fast: false
      matrix:
        include:
          - network: "fork9-cdk-validium"
            filter_tags: "light,batch-verification,danger,access-list"
            deploy_infra: true
            gas_token_addr: "0x72ae2643518179cF01bcA3278a37ceAD408DE8b2"

          - network: "fork11-rollup"
            filter_tags: "all"
            deploy_infra: true

          - network: "fork12-cdk-validium"
            filter_tags: "light,batch-verification,erc20-tests,heavy,zk-counters-tests"
            deploy_infra: true

          - network: "fork12-rollup"
            filter_tags: "light,batch-verification,eoa-transaction,heavy,zk-counters-tests"
            deploy_infra: true

    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        pip3 install yq
        yq --version

    - name: Install Kurtosis
      if: matrix.deploy_infra
      run: |
        echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
        sudo apt update
        sudo apt install kurtosis-cli=1.4.1
        kurtosis version

    - name: Disable kurtosis analytics
      if: matrix.deploy_infra
      run: kurtosis analytics disable

    - name: Deploy Kurtosis Devnet
      if: matrix.deploy_infra
      run: ./core/helpers/setup-kurtosis.sh "${{ matrix.network }}"

    - name: Install runner
      run: make install-runner

    - name: Run E2E Tests
      run: polygon-test-runner --filter-tags "${{ matrix.filter_tags }}"
      env:
        GAS_TOKEN_ADDR: ${{ matrix.gas_token_addr }}
        L2_RPC_URL: ${{ env.L2_RPC_URL }}
