name: Test e2e

on:
  push:
    branches:
      - "**"
  schedule:
    - cron: "0 2 * * *" # Run nightly at 2 AM UTC
  workflow_dispatch: {}

jobs:
  call-cdk-e2e:
    uses: ./.github/workflows/cdk-e2e.yml

  test-e2e:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Kurtosis CDK.
          - package: kurtosis-cdk
            version: v0.4.0
            args_file: .github/tests/chains/op-succinct.yml
            filter_tags: batch-verification,gas-limit-overflow,access-list

          # Kurtosis Polygon PoS.
          - package: kurtosis-polygon-pos
            version: v1.0.6
            args_file: .github/tests/heimdall-bor-multi-validators.yml
            filter_tags: pos,bridge
          - package: kurtosis-polygon-pos
            version: v1.0.6
            args_file: .github/tests/heimdall-v2-bor-multi-validators.yml
            filter_tags: pos,bridge

    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      L2_SENDER_PRIVATE_KEY: ${{ matrix.env.L2_SENDER_PRIVATE_KEY || '0x12d7de8621a77640c9241b2595ba78ce443d05e94090365ab3bb5e19df82c625' }}
      CUSTOM_AGGLAYER_IMAGE: ${{ matrix.custom_agglayer_image || '' }}

    steps:
      - uses: actions/checkout@v4

      - name: Install kurtosis
        run: |
          echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
          sudo apt update
          sudo apt install kurtosis-cli=1.4.4
          kurtosis version
          kurtosis analytics disable

      - name: Install jq
        run: sudo apt update && sudo apt install --yes jq && jq --version

      - name: Install yq
        run: pip3 install yq && yq --version

      - name: Install shellcheck
        run: sudo apt update && sudo apt install --yes shellcheck && shellcheck --version

      - name: Install polycli
        run: |
          POLYCLI_VERSION="v0.1.74"
          tmp_dir=$(mktemp -d)
          curl -L "https://github.com/0xPolygon/polygon-cli/releases/download/${POLYCLI_VERSION}/polycli_${POLYCLI_VERSION}_linux_amd64.tar.gz" | tar -xz -C "$tmp_dir"
          mv "$tmp_dir"/* /usr/local/bin/polycli
          rm -rf "$tmp_dir"
          sudo chmod +x /usr/local/bin/polycli
          /usr/local/bin/polycli version

      - name: Install foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
        env:
          GOARCH: amd64

      - name: Setup bats
        uses: bats-core/bats-action@2.0.0

      - name: Deploy devnet
        run: ./core/helpers/setup-kurtosis.sh "${{ matrix.package }}" "${{ matrix.version }}" "${{ matrix.args_file }}"

      - name: Run e2e tests
        run: ENCLAVE=cdk bats --filter-tags ${{ matrix.filter_tags }} --recursive tests/

      - name: Dump enclave logs
        if: always()
        run: kurtosis dump ./dump

      - name: Generate archive name
        if: always()
        run: |
          file_name=$(basename "${{ matrix.args_file }}" ".yml")
          archive_name="dump_run_with_args_${{ matrix.package }}_${file_name}_${{ github.run_id }}_${{ strategy.job-index }}"
          echo "ARCHIVE_NAME=${archive_name}" >> "$GITHUB_ENV"

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARCHIVE_NAME }}
          path: ./dump
